languages = ["java", "python"]
sandBoxRunParams = ["go", "run", "/usercode/codeRunner.go"]
imageName = "compiler_machine"
mountPoint = "/usercode"
sandBoxLocation = "sandbox"
payloadLocation = "payload"
tempFileName = "temp"
codeFilename = "file"
inputFileName = "inputFile"
[languageExtensions]
java = { extension = ".java", execCommand = "java" }
python = { extension = ".py", execCommand = "python" }
python3 = { extension = ".py", execCommand = "python3" }